### PR TITLE
fixed getFreePhysicalMemory

### PR DESCRIPTION
**Pull request by jingluoguo**
Fix the bug that the getFreePhysicalMemory method cannot get the value

### CODE REVIEW

**Comment by Holofox** [comment]
@bsutton, look please

**Comment by bsutton** [comment]
Thanks for the pr.

Will try to release it over the weekend.

**Comment by bsutton** [comment]
publish to pub.dev as 2.0.4.

once again, greatly appreciate the patch.

**Comment by jingluoguo** [comment]
sure

**Pull request merged**
